config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'sign_up', to: 'users#new'
  get 'sign_in', to: 'sessions#new'
  delete 'sign_out', to: 'sessions#destroy'

  resources :places
  resources :users
  resources :sessions
  resources :password_resets

  root 'static_pages#home'

end

app/models/place.rb
class Place < ActiveRecord::Base
  validates :name, :description, { presence: true }
  validates :description, length: { maximum: 400 }

  geocoded_by :address
  after_validation :geocode

  belongs_to :user

  mount_uploader :image, PlaceImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :email, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  has_many :places, dependent: :destroy

  has_secure_password

  def set_reset_password_token
    self.reset_password_token = loop do
      token = SecureRandom.hex
      break token unless self.class.exists?(reset_password_token: token)
    end
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  helper_method :user_logged_in?, :current_user, :owned_by?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_logged_in?
    current_user
  end

  def owned_by?(user)
    user_logged_in? && current_user == user
  end

  def authorize
    unless user_logged_in?
      redirect_to sign_in_url,
        alert: 'You are not authorized! Please login first!'
    end
  end
  
  def authorize_owner
    place_owner = Place.find(params[:id]).user
    unless user_logged_in? && current_user == place_owner
      redirect_to root_url,
        alert: 'You are not authorized to perform the action!'
    end
  end

  def authorize_profile
    profile_owner = User.find(params[:id])
    unless user_logged_in? && current_user == profile_owner
      redirect_to root_url,
        alert: 'You are not authorized to perform the action!'
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    
    if user
      user.set_reset_password_token
      UserMailer.reset_password(user.id).deliver_later
      redirect_to root_url, notice: 'Please check your email'
    else
      redirect_to new_password_reset_url, alert: 'Email not found in our system'
    end
  end

  def edit
    @user = User.find_by(reset_password_token: params[:token]) if params[:token]

    redirect_to root_url,
      alert: 'You have invalid token, please redo the process' unless @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      @user.update_attribute(:reset_password_token, nil)
      redirect_to sign_in_url, notice: 'Please login with your new password'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authorize, except: [:index, :show]
  before_action :authorize_owner, only: [:edit, :update, :destroy]

  def index
    @places = Place.page(params[:page]).per(5)
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.build(place_params)

    if @place.save
      redirect_to places_url, notice: 'Place created!'
    else
      render :new
    end
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])

    if @place.update(place_params)
      redirect_to places_url, notice: 'Place updated!'
    else
      render :edit
    end
  end

  def destroy
    Place.find(params[:id]).destroy

    redirect_to places_url, notice: 'Place deleted!'
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :image, :address)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_url(user), notice: 'Signed in successfully!'
    else
      redirect_to sign_in_url, alert: 'Wrong email or password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed out successfully!'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    # Grab the 8 last updated places
    # Other query that you might use
    # Grap 8 latest created places => Place.last(8)
    @places = Place.order(updated_at: :desc).limit(8)
    @markers = @places.select{|p| p.latitude.present? && p.longitude.present?}.map{|p| "&markers=#{p.latitude},#{p.longitude}"}.join
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:edit, :update, :destroy]
  before_action :authorize_profile, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User created!'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: 'User updated!'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.erb
<footer>
<small>
  Belajar Rails 2
</small>
<nav>
  <ul>
    <li><%= link_to 'About', about_path %></li>
  </ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to 'Kostly', root_path, class: 'navbar-brand', id: 'logo' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Browse', places_path %></li>
        <% if user_logged_in? %>
          <li><%= link_to 'My Places', current_user %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hi <%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign In', sign_in_path %></li>
          <li><%= link_to 'Sign Up', sign_up_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= yield(:title) %> | Kostly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class='container'>
    <% if notice %>
      <div class='alert alert-success'><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class='alert alert-danger'><%= alert %></div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </div>


</body>
</html>

app/views/layouts/pages.html.erb
<h2>This is static pages layout</h2>
<%= yield %>

app/views/password_resets/edit.html.erb
<% provide :title, 'Edit Password' %>

<h2>Enter Your New Password</h2>
<%= form_for @user, url: password_reset_path(@user) do |f| %>
  <div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  <div>

  <div class='form-group'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Reset my Password', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/password_resets/new.html.erb
<% provide :title, 'Password Reset' %>

<h2>Reset Your Password</h2>
<%= form_tag :password_resets do %>
  <div class='form-group'>
    <%= label_tag :email %>
    <%= email_field_tag :email, '', class: 'form-control' %>
  </div>

  <%= submit_tag 'Send Password Reset Instruction to My Email', class: 'btn btn-primary btn-block' %>
<% end %>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>

  <% if @place.errors.any? %>
    <div class='alert alert-danger'>
      <strong><%= pluralize @place.errors.count, 'error' %> prevented place to be submitted </strong>
      <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit class: 'btn btn-primary btn-block' %>
<% end %>

app/views/places/edit.html.erb
<h2>Edit place</h2>
<%= render 'form' %>

app/views/places/index.html.erb
<% provide :title, 'Browse for Places' %>

<h1>Listing Places</h1>
<% if user_logged_in? %>
  <%= link_to 'Add Place', new_place_path, class: 'btn btn-primary' %>
<% end %>
<table class='table table-striped'>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Posted By</th>
      <th>Description</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.id %></td>
        <td><%= place.name %></td>
        <td><%= link_to place.user.name, place.user %></td>
        <td><%= place.description %></td>
        <td width='30%'>
          <div class='btn-group'>
            <%= link_to 'View', place_path(place), class: 'btn btn-default' %>
            <% if user_logged_in? && owned_by?(place.user) %>
              <%= link_to 'Edit', edit_place_path(place), class: 'btn btn-default' %>
              <%= link_to 'Delete', place_path(place), class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @places %>

app/views/places/new.html.erb
<h2>Submit your place!</h2>
<%= render 'form' %>

app/views/places/show.html.erb
<% provide :title, @place.name %>

<h2>
  <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
  <%= @place.name %>
</h2>
<% if @place.latitude && @place.longitude %>
  <p>
  <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
  <%= link_to @place.address, "http://maps.google.com/?q=#{@place.latitude},#{@place.longitude}" %>
  </p>
<% end %>
<div class="row">
  <div class="columns col-md-3">
    <%= image_tag @place.image.url, size: '250x250', alt: @place.name %>
  </div>
  <div class="columns col-md-9">
    <blockquote><small><%= @place.description %></small></blockquote>
    <% if @place.latitude && @place.longitude %>
      <h3>Nearby Locations</h3>
      <ul>
        <% @place.nearbys(10).each do |place| %>
          <li><%= link_to place.name, place %> (<%= place.distance.round(2) %> km)</li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>
<div class="pull-right">
  <%= gravatar_for @place.user, size: 20 %>
  <small>By: <%= link_to @place.user.name, @place.user %></small>
  <p><em>Posted <%= time_ago_in_words @place.created_at %> ago</em></p>
</div>

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>
<h1>Tentang Kostly</h1>
<p>Kostly adalah platform mencari rumah, kostan, atau tanah idaman anda</p>

app/views/static_pages/home.html.erb
<% provide :title, 'Home' %>

<div class="row">
  <div class="col-md-12 columns text-center">
    <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=Yogyakarta,Indonesia&zoom=12&size=500x200&maptype=roadmap&scale=2#{@markers}" %>
  <hr>
  </div>
</div>
<div class="row">
  <% @places.each do |place| %>
    <div class="col-md-3 columns place-item">
      <%= image_tag place.image.url, size: '200x150', alt: place.name, class: 'img-thumbnail' %>
      <h2><%= link_to place.name, place %></h2>
      <p><em>Posted at: <%= time_ago_in_words place.created_at %> ago</em></p>
      <p><%= truncate place.description, length: 50  %></p>
      <div class="pull-right">
        <%= gravatar_for place.user, size: 20 %>
        <small>By: <%= link_to place.user.name, place.user %></small>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class='alert alert-danger'>
      <strong><%= pluralize @user.errors.count, 'error' %> prevented user to be submitted </strong>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary btn-block' %>
<% end %>

app/views/users/edit.html.erb
<% provide :title, 'Edit Profile' %>

<h2>Edit Profile</h2>
<%= render 'form' %>

app/views/users/new.html.erb
<% provide :title, 'Register' %>

<h2>Register</h2>
<%= render 'form' %>

app/views/users/show.html.erb
<% provide :title, @user.name %>

<h2>
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
  <%= @user.name %>
</h2>
<div class="row">
  <div class="columns col-md-5">
    <div class="row">
      <div class="columns col-md-3">
        <%= gravatar_for @user, size: 100 %>
      </div>
      <div class="columns col-md-9">
        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        Email: <%= mail_to @user.email %>
      </div>
    </div>
  </div>
  <div class="col-md-7">
    <% if @user.places.any? %>
      <h3>
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
        Places (<%= @user.places.count %>)
      </h3>
      <ul>
        <% @user.places.each do |place| %>
          <li><%= link_to place.name, place %></li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>